---
- hosts: all
  vars:
    plugins:
    - ldap
    - gravatar
    - simple-theme-plugin
    - ansicolor
    - git
    - github
    - ghprb
    - instant-messaging
    - ircbot
    - cobertura
    - greenballs
    - envinject
    - shiningpanda
    - notification
    hostname: jenkins.jupyter.org
    server_credential_root: /etc/ssl/private
    server_cert: jupyter.org.crt
    server_key: jupyter.org.key
    jenkins_username: jenkins
    jenkins_home: /var/lib/jenkins
    ansible_version: 1.4.5
    java_version: "openjdk-8"
  vars_files:
    - credentials.yml
  roles:
  - jenkins
  - nginx
  - python
